---
- name: Install Apache/PHP
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - libapache2-mod-php5
    - php5-cli
    - php5-curl
    - php5-gd
    - php5-mysql
    - php5-sqlite
    - php5-xdebug

- name: Set /var/lock/apache2 owner
  file: path=/var/lock/apache2 recurse=yes state=directory group={{ apache_group }} owner={{ apache_user }}
  sudo: yes

- name: Set Apache user and group
  lineinfile: >
    dest=/etc/apache2/envvars
    regexp="{{ item.key }}"
    line="{{ item.value }}"
    state=present
  with_items:
   - { key: "^export APACHE_RUN_USER=", value: "export APACHE_RUN_USER={{ apache_user }}" }
   - { key: "^export APACHE_RUN_GROUP=", value: "export APACHE_RUN_GROUP={{ apache_group }}" }
  notify:
   - apache-restart
  sudo: yes

- name: Make sure apache_root exists
  file:
    path={{ apache_root }}
    state=directory
    group={{ apache_group }}
    owner={{ apache_user }}
  sudo: yes

- name: Copy phpinfo.hp
  template: src={{ item }} dest={{ apache_root }}/{{ item }} owner={{ apache_user }} group={{ apache_group }} mode=0644
  with_items:
    - phpinfo.php

- name: Apache | Enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
    - rewrite
    - php5
    - autoindex
    - ssl
  sudo: yes
  notify: apache-restart

- name: Delete default Apache vhost
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  sudo: yes
  notify: apache-restart

- name: Push default virtualhost configuration template
  template:
    src=default_virtualhost.conf.j2
    dest=/etc/apache2/sites-available/default-vhost.conf
  notify: apache-restart
  sudo: yes

- name: Create ssl directory
  file: path=/etc/apache2/ssl state=directory group={{ apache_group }} owner={{ apache_user }}
  sudo: yes

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN=${ansible_fqdn}" -days 3650 -keyout /etc/apache2/ssl/server.key -out /etc/apache2/ssl/server.crt -extensions v3_ca creates=/etc/apache2/ssl/server.crt

- name: Apache | Enable Sites
  command: a2ensite {{ item }} creates=/etc/apache2/sites-enabled/{{ item }}
  with_items:
    - default-vhost
  sudo: yes
  notify: apache-reload

- name: Configure PHP
  template: src={{ item }} dest=/etc/php5/mods-available/{{ item }} owner=root group=root mode=0644
  with_items:
    - opcache.ini
    - debug.ini
  sudo: yes

- name: Configure PHP Apace module
  file: src=/etc/php5/mods-available/{{ item.src }} dest=/etc/php5/apache2/conf.d/{{ item.dest }} owner=root group=root mode=0644 state=link
  with_items:
    - { src: opcache.ini, dest: 05-opcache.ini }
    - { src: debug.ini, dest: 99-debug.ini}
  sudo: yes
  notify: apache-restart

- name: Configure PHP-CLI
  template: src={{ item.src }} dest=/etc/php5/cli/conf.d/{{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: opcache.ini, dest: 05-opcache.ini }
    - { src: debug.ini, dest: 99-debug.ini}
  sudo: yes

- name: be sure apache is started and enabled
  service: name=apache2 state=started enabled=yes
  sudo: yes

- name: Setup Owner
  file: path={{ apache_root }} owner=vagrant group=users recurse=true
  sudo: yes
