---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: remove packages
  apt: pkg={{ item }} state=absent
  sudo: yes
  with_items:
    - chef

- name: upgrade the distro
  apt: upgrade=yes
  sudo: yes

- name: install packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - sudo
    - bash-completion
    - python-pycurl
    - git
    - htop
    - tree
    - vim
    - curl
    - zip
    - rsync
    - wget
    - python-software-properties
    - unattended-upgrades
    - ant
    - cowsay
    - tmux
    - avahi-daemon
    - php5-sqlite
    - php5-xdebug
    - openjdk-7-jdk-headless

- name: copy tmux config
  template: src=tmux.conf dest=~/.tmux.conf

- name: be sure ntp is installed
  apt: pkg=ntp state=installed
  tags: ntp
  sudo: yes

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp
  sudo: yes

- name: Add a ~/bin to PATH
  lineinfile: dest=~/.bashrc line='PATH="$HOME/bin:$PATH"'

- name: Make sure ~/bin exists
  file: path=~/bin state=directory

- name: Copy common files to ~/bin
  copy: src={{ item }} dest=~/bin/  mode=755
  with_fileglob:
    - bin/*
