---
- name: Wait for automatic system updates
  become: yes
  shell: 	while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done;

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: remove packages
  apt: pkg={{ item }} state=absent
  become: yes
  with_items:
    - chef
    - puppet

- name: upgrade the distro
  apt: upgrade=dist
  become: yes

- name: install packages
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - sudo
    - bash-completion
    - python-pycurl
    - git
    - htop
    - tree
    - vim
    - curl
    - zip
    - rsync
    - wget
    - python-software-properties
    - unattended-upgrades
    - ant
    - tmux
    - avahi-daemon
    - openjdk-9-jre-headless
    - libjpeg-progs
    - jpegoptim
    - pngcrush
    - optipng

- name: copy tmux config
  template: src=tmux.conf dest=~/.tmux.conf

- name: be sure ntp is installed
  apt: pkg=ntp state=installed
  tags: ntp
  become: yes

- name: be sure ntpd is running and enabled
  service: name=ntp state=started enabled=yes
  tags: ntp
  become: yes

- name: Enable git support in bash prompt
  blockinfile: 
    path: ~/.bashrc
    block: |
      if [ -f /etc/bash_completion.d/git-prompt ]; then
          case "$TERM" in
                  xterm-color|*-256color) color_prompt=yes;;
          esac
      
          if [ "$color_prompt" = yes ]; then
                  PS1=$PS1'$(__git_ps1 "\[\e[0;32m\](%s) \[\e[0m\]")'
          else
                  PS1=$PS1'$(__git_ps1 "(%s) ")'
          fi
          unset color_prompt
      fi
