---
#- name: create ionCube install dir
#  file: path="{{ ioncube_install_path }}" state=directory
#  become: yes

- name: Download IonCube loaders
  get_url:
    url: "{{ ioncube_download_url }}"
    dest: "{{ ioncube_install_path }}/ioncube_loaders.tar.gz"
  become: yes

- name: Extract IonCube Loaders
  unarchive:
    src: "{{ ioncube_install_path }}/ioncube_loaders.tar.gz"
    dest: "{{ ioncube_install_path }}"
    copy: no
    creates: "{{ ioncube_install_path }}/ioncube/README.txt"
  become: yes

#- name: Clean up downloaded files
#  file: path="{{ ioncube_install_path }}/ioncube_loaders.tar.gz" state=absent
#  become: yes

- name: create php.ini entry
  shell: echo "zend_extension={{ ioncube_install_path }}/ioncube/ioncube_loader_lin_{{ php_version }}.so" > /etc/php/{{ php_version }}/mods-available/ioncube.ini
  args:
    creates: /etc/php/{{ php_version }}/mods-available/ioncube.ini
  become: yes

- name: Enable IonCube for Apache 2 PHP Module
  file: path=/etc/php/{{ php_version }}/apache2/conf.d/00-ioncube.ini src=/etc/php/{{ php_version }}/mods-available/ioncube.ini state=link
  become: yes

- name: Enable IonCube for php-cli
  file: path=/etc/php/{{ php_version }}/cli/conf.d/00-ioncube.ini src=/etc/php/{{ php_version }}/mods-available/ioncube.ini state=link
  become: yes

- name: Disable php-opcache for Apache 2 PHP Module
  file: path=/etc/php/{{ php_version }}/apache2/conf.d/10-opcache.ini state=absent
  become: yes
