---
shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.7_741ae9fb77ecb227dc6be9c1028ded1e957c0e14.zip # 5.3.7
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.6_c3d6cecc4dcbd0480a289006fdd4c643bfddb49c.zip # 5.3.6
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.5_233d40b70fe2198b48d68793af3cf1421568b345.zip # 5.3.5
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.4_05cdb056b32446d2bb555aa00f85aac06ec72060.zip # 5.3.4
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.3_0e50204087219ada9cdd9a74cd17cbb264e8c0a4.zip # 5.3.3
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.2_5ab7c48a261445eaeb25273cb34c1a6ae3102741.zip # 5.3.2
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.1_e42b3bfc041e6115ae04948dccbd1cd91d5c0564.zip # 5.3.1
#shopware5_download_url: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.3.0_51914cdfbd690d51f3dbe4049705b033ff98811f.zip # 5.3.0

shopware5_install_path: "{{ web_root }}/shopware5"
shopware5_db_host: "localhost"
shopware5_db_port: "3306"
shopware5_db_name: "shopware5"
shopware5_db_pass: "shopware5"
shopware5_db_user: "shopware5"
shopware5_app_path: "/shopware5"
shopware5_app_host: "{{ app_host }}"
shopware5_php_error_reporting: "E_ALL & ~E_NOTICE & ~E_DEPRECATED"
