---
- name: apply common configuration to all nodes
  hosts: all
  roles:
    #- shopware5
    #- shopware51
    #- shopware52
    #- jtlshop4
    #- wordpress
    - blank
  vars:
    php_version: 7.0 # 5.6 or 7.0
